spring.application.name=transactguard

spring.datasource.url=jdbc:postgresql://localhost:5432/transactguard
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=postgres
spring.datasource.password=Ofentse

spring.security.user.name=user
spring.security.user.password=user

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




